# travis-ci.org build & test configuration
language: python

python:
    - "2.7"
    #- "3.2"

env:
    #- ROOT=5-32-00
    #- ROOT=5-32-01
    #- ROOT=5-32-02
    #- ROOT=5-32-03
    - ROOT=5-32-04
    #- ROOT=5-33-02
    #- ROOT=5-33-02b
    #- ROOT=5-34-00
    #- ROOT=5-34-04
    #- ROOT=5-34-05
    #- ROOT=5-34-06
    #- ROOT=5-34-07
    - ROOT=5-34-08
    #- ROOT=5-99-02

before_install:
    # Use system python, not virtualenv, because building the dependencies from source takes too long
    - deactivate # the virtualenv

    # Needed because sometimes travis' repositories get out of date
    - time sudo apt-get update -qq
    - time sudo apt-get install python-pip
    - time sudo pip install coverage
    - time sudo pip install coveralls

install:
    # Check if we are running Python 2 or 3. This is needed for the apt-get package names
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then export PYTHON_SUFFIX="3"; fi

    # Install the dependencies we need
    - time sudo apt-get install -qq python${PYTHON_SUFFIX}-numpy python${PYTHON_SUFFIX}-sphinx python${PYTHON_SUFFIX}-nose

    # Install a ROOT binary that we custom-built in a 64-bit Ubuntu VM
    # for the correct Python / ROOT version
    - time wget --no-check-certificate https://copy.com/rtIyUdxgjt7h/ci/root_builds/root_v${ROOT}_python_${TRAVIS_PYTHON_VERSION}.tar.gz
    - time tar zxf root_v${ROOT}_python_${TRAVIS_PYTHON_VERSION}.tar.gz
    - mv root_v${ROOT}_python_${TRAVIS_PYTHON_VERSION} root
    - source root/bin/thisroot.sh

script:
    # Check if root and PyROOT work ok
    - time root -l -q
    - time python -c 'import ROOT; ROOT.TBrowser()'

    # Now run the actual tests (from the installed version, not the local build dir)
    - time make install-user
    - time make test-installed
    - time make doc

    # run tests with coverage
    - time make test-coverage

after_success:
    - time coveralls
